FROM 	 stakater/nginx:latest

RUN export DEBIAN_FRONTEND=noninteractive

ARG    CONSUL_TEMPLATE_VERSION=0.39.1

RUN 	 rm -rf /etc/nginx/sites-available/

ENV 	 CONSUL_URL consul:8500

ADD 	 https://releases.hashicorp.com/consul-template/${CONSUL_TEMPLATE_VERSION}/consul-template_${CONSUL_TEMPLATE_VERSION}_linux_amd64.zip /usr/bin/
RUN 	 unzip /usr/bin/consul-template_${CONSUL_TEMPLATE_VERSION}_linux_amd64.zip && \
    	 mv consul-template /usr/local/bin/consul-template && \
    	 rm -rf /usr/bin/consul-template_${CONSUL_TEMPLATE_VERSION}_linux_amd64.zip

VOLUME  templates

EXPOSE 	80

RUN     mkdir -p /etc/service/nginx && rm -rf /etc/service/nginx/*

ADD     start.sh /etc/service/nginx/run

CMD ["/sbin/my_init"]
