version: "3.8"

services:
  mongo-configsvr-1:
    image: mongo:7
    container_name: mongo-configsvr-1
    hostname: mongo-configsvr-1
    command: ["--configsvr", "--replSet", "config-replica-set", "--bind_ip_all", "--port", "40001"]
    ports:
      - 40001:40001
    volumes:
      - mongo-configsvr-1:/data/db

  mongo-configsvr-2:
    image: mongo:7
    container_name: mongo-configsvr-2
    hostname: mongo-configsvr-2
    command: ["--configsvr", "--replSet", "config-replica-set", "--bind_ip_all", "--port", "40002"]
    ports:
      - 40002:40002
    volumes:
      - mongo-configsvr-2:/data/db

  mongo-configsvr-3:
    image: mongo:7
    container_name: mongo-configsvr-3
    hostname: mongo-configsvr-3
    command: ["--configsvr", "--replSet", "config-replica-set", "--bind_ip_all", "--port", "40003"]
    ports:
      - 40003:40003
    volumes:
      - mongo-configsvr-3:/data/db

  mongo-shard-1-rs-1:
    image: mongo:7
    container_name: mongo-shard-1-rs-1
    hostname: mongo-shard-1-rs-1
    command: ["--shardsvr", "--replSet", "shard-replica-set-1", "--bind_ip_all", "--port", "40011"]
    ports:
      - 40011:40011
    volumes:
      - mongo-shard-1-rs-1:/data/db

  mongo-shard-1-rs-2:
    image: mongo:7
    container_name: mongo-shard-1-rs-2
    hostname: mongo-shard-1-rs-2
    command: ["--shardsvr", "--replSet", "shard-replica-set-1", "--bind_ip_all", "--port", "40012"]
    ports:
      - 40012:40012
    volumes:
      - mongo-shard-1-rs-2:/data/db

  mongo-shard-1-rs-3:
    image: mongo:7
    container_name: mongo-shard-1-rs-3
    hostname: mongo-shard-1-rs-3
    command: ["--shardsvr", "--replSet", "shard-replica-set-1", "--bind_ip_all", "--port", "40013"]
    ports:
      - 40013:40013
    volumes:
      - mongo-shard-1-rs-3:/data/db
      

  mongo-shard-2-rs-1:
    image: mongo:7
    container_name: mongo-shard-2-rs-1
    hostname: mongo-shard-2-rs-1
    command: ["--shardsvr", "--replSet", "shard-replica-set-2", "--bind_ip_all", "--port", "40021"]
    ports:
      - 40021:40021
    volumes:
      - mongo-shard-2-rs-1:/data/db

  mongo-shard-2-rs-2:
    image: mongo:7
    container_name: mongo-shard-2-rs-2
    hostname: mongo-shard-2-rs-2
    command: ["--shardsvr", "--replSet", "shard-replica-set-2", "--bind_ip_all", "--port", "40022"]
    ports:
      - 40022:40022
    volumes:
      - mongo-shard-2-rs-2:/data/db

  mongo-shard-2-rs-3:
    image: mongo:7
    container_name: mongo-shard-2-rs-3
    hostname: mongo-shard-2-rs-3
    command: ["--shardsvr", "--replSet", "shard-replica-set-2", "--bind_ip_all", "--port", "40023"]
    ports:
      - 40023:40023
    volumes:
      - mongo-shard-2-rs-3:/data/db
      
  mongo-shard-3-rs-1:
    image: mongo:7
    container_name: mongo-shard-3-rs-1
    hostname: mongo-shard-3-rs-1
    command: ["--shardsvr", "--replSet", "shard-replica-set-3", "--bind_ip_all", "--port", "40031"]
    ports:
      - 40031:40031
    volumes:
      - mongo-shard-3-rs-1:/data/db

  mongo-shard-3-rs-2:
    image: mongo:7
    container_name: mongo-shard-3-rs-2
    hostname: mongo-shard-3-rs-2
    command: ["--shardsvr", "--replSet", "shard-replica-set-3", "--bind_ip_all", "--port", "40032"]
    ports:
      - 40032:40032
    volumes:
      - mongo-shard-3-rs-2:/data/db

  mongo-shard-3-rs-3:
    image: mongo:7
    container_name: mongo-shard-3-rs-3
    hostname: mongo-shard-3-rs-3
    command: ["--shardsvr", "--replSet", "shard-replica-set-3", "--bind_ip_all", "--port", "40033"]
    ports:
      - 40033:40033
    volumes:
      - mongo-shard-3-rs-3:/data/db
      
  mongos-shard:
    image: mongo:7
    container_name: mongos-shard
    hostname: mongos-shard
    command: mongos --configdb config_rs/mongo-configsvr-1:40001,mongo-configsvr-2:40002,mongo-configsvr-3:40003 --bind_ip_all --port 27017
    ports:
      - 40100:27017


  
