
version: '3'

services:
  mongos:
    container_name: mongos
    image: mongo:latest
    command: mongos --configdb config-replica-set/mongo-configsvr-1:40001,mongo-configsvr-2:40002,mongo-configsvr-3:40003 --port 27017
    ports:
      - 30000:27017
